using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Parser;

namespace Generator
{
    [Generator]
    public class Generator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            JavaParser parser = new JavaParser();
            List<MethodDeclaration> list = parser.ParserController(
                @"/Users/kate/Desktop/demo/src/main/java/com/example/demo/controller/ProjectController.java");

            var methods = new MemberDeclarationSyntax[list.Count];
            int globalI = 0;

            foreach (var methodDeclaration in list)
            {
                if (methodDeclaration.HttpMethodName == "get")
                {
                    int countParameter = 0;
                    SyntaxNodeOrToken[] argArray = new SyntaxNodeOrToken[methodDeclaration.ArgList.Count];
                    string newUrl = methodDeclaration.Url + "?";
                    foreach (var arg in methodDeclaration.ArgList)
                    {
                        var parameter = SyntaxFactory.Parameter(
                                SyntaxFactory.Identifier(arg.Name)
                            )
                            .WithType(
                                SyntaxFactory.IdentifierName(arg.Type)
                            ).NormalizeWhitespace();

                        argArray[countParameter] = parameter;

                        newUrl = newUrl + $"{arg.Name}={{{arg.Name}}}&";
                        countParameter++;
                    }

                    var httpRequest =
                        SyntaxFactory.InterpolatedStringText()
                            .WithTextToken(
                                SyntaxFactory.Token(
                                    SyntaxFactory.TriviaList(),
                                    SyntaxKind.InterpolatedStringTextToken,
                                    newUrl,
                                    newUrl,
                                    SyntaxFactory.TriviaList()
                                )
                            ).NormalizeWhitespace();


                    var method =
                        SyntaxFactory.MethodDeclaration(
                                SyntaxFactory.IdentifierName(methodDeclaration.ReturnType),
                                    SyntaxFactory.Identifier(methodDeclaration.MethodName)
                                )
                            .WithModifiers(
                                SyntaxFactory.TokenList(
                                    SyntaxFactory.Token(SyntaxKind.PublicKeyword)
                                )
                            )
                            .WithParameterList(
                                SyntaxFactory.ParameterList(
                                    SyntaxFactory.SeparatedList<ParameterSyntax>(
                                        argArray
                                    )
                                )
                            )
                            .WithBody(
                                SyntaxFactory.Block(
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName("HttpWebRequest")
                                            )
                                            .WithVariables(
                                                SyntaxFactory.SingletonSeparatedList<VariableDeclaratorSyntax>(
                                                    SyntaxFactory.VariableDeclarator(
                                                            SyntaxFactory.Identifier("req")
                                                        )
                                                        .WithInitializer(
                                                            SyntaxFactory.EqualsValueClause(
                                                                SyntaxFactory.CastExpression(
                                                                    SyntaxFactory.IdentifierName("HttpWebRequest"),
                                                                    SyntaxFactory.InvocationExpression(
                                                                            SyntaxFactory.MemberAccessExpression(
                                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                                SyntaxFactory.IdentifierName(
                                                                                    "WebRequest"),
                                                                                SyntaxFactory.IdentifierName("Create")
                                                                            )
                                                                        )
                                                                        .WithArgumentList(
                                                                            SyntaxFactory.ArgumentList(
                                                                                SyntaxFactory
                                                                                    .SingletonSeparatedList<
                                                                                        ArgumentSyntax>(
                                                                                        SyntaxFactory.Argument(
                                                                                            SyntaxFactory
                                                                                                .InterpolatedStringExpression(
                                                                                                    SyntaxFactory.Token(
                                                                                                        SyntaxKind
                                                                                                            .InterpolatedStringStartToken)
                                                                                                )
                                                                                                .WithContents(
                                                                                                    SyntaxFactory
                                                                                                        .SingletonList<
                                                                                                            InterpolatedStringContentSyntax>(
                                                                                                            httpRequest
                                                                                                        )
                                                                                                )
                                                                                        )
                                                                                    )
                                                                            )
                                                                        )
                                                                )
                                                            )
                                                        )
                                                )
                                            )
                                    ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName("WebResponse")
                                            )
                                            .WithVariables(
                                                SyntaxFactory
                                                    .SingletonSeparatedList<
                                                        VariableDeclaratorSyntax>(
                                                        SyntaxFactory.VariableDeclarator(
                                                                SyntaxFactory.Identifier("resp")
                                                            )
                                                            .WithInitializer(
                                                                SyntaxFactory.EqualsValueClause(
                                                                    SyntaxFactory
                                                                        .InvocationExpression(
                                                                            SyntaxFactory
                                                                                .MemberAccessExpression(
                                                                                    SyntaxKind
                                                                                        .SimpleMemberAccessExpression,
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "req"),
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "GetResponse")
                                                                                )
                                                                        )
                                                                )
                                                            )
                                                    )
                                            )
                                    ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName("Stream")
                                            )
                                            .WithVariables(
                                                SyntaxFactory
                                                    .SingletonSeparatedList<
                                                        VariableDeclaratorSyntax>(
                                                        SyntaxFactory.VariableDeclarator(
                                                                SyntaxFactory.Identifier(
                                                                    "stream")
                                                            )
                                                            .WithInitializer(
                                                                SyntaxFactory.EqualsValueClause(
                                                                    SyntaxFactory
                                                                        .InvocationExpression(
                                                                            SyntaxFactory
                                                                                .MemberAccessExpression(
                                                                                    SyntaxKind
                                                                                        .SimpleMemberAccessExpression,
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "resp"),
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "GetResponseStream")
                                                                                )
                                                                        )
                                                                )
                                                            )
                                                    )
                                            )
                                    ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName("StreamReader")
                                            )
                                            .WithVariables(
                                                SyntaxFactory
                                                    .SingletonSeparatedList<
                                                        VariableDeclaratorSyntax>(
                                                        SyntaxFactory.VariableDeclarator(
                                                                SyntaxFactory.Identifier("sr")
                                                            )
                                                            .WithInitializer(
                                                                SyntaxFactory.EqualsValueClause(
                                                                    SyntaxFactory
                                                                        .ObjectCreationExpression(
                                                                            SyntaxFactory
                                                                                .IdentifierName(
                                                                                    "StreamReader")
                                                                        )
                                                                        .WithArgumentList(
                                                                            SyntaxFactory
                                                                                .ArgumentList(
                                                                                    SyntaxFactory
                                                                                        .SingletonSeparatedList
                                                                                            <ArgumentSyntax>(
                                                                                                SyntaxFactory
                                                                                                    .Argument(
                                                                                                        SyntaxFactory
                                                                                                            .IdentifierName(
                                                                                                                "stream")
                                                                                                    )
                                                                                            )
                                                                                )
                                                                        )
                                                                )
                                                            )
                                                    )
                                            )
                                    ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.PredefinedType(
                                                    SyntaxFactory.Token(
                                                        SyntaxKind.StringKeyword)
                                                )
                                            )
                                            .WithVariables(
                                                SyntaxFactory
                                                    .SingletonSeparatedList<
                                                        VariableDeclaratorSyntax>(
                                                        SyntaxFactory.VariableDeclarator(
                                                                SyntaxFactory.Identifier(
                                                                    "output")
                                                            )
                                                            .WithInitializer(
                                                                SyntaxFactory.EqualsValueClause(
                                                                    SyntaxFactory
                                                                        .InvocationExpression(
                                                                            SyntaxFactory
                                                                                .MemberAccessExpression(
                                                                                    SyntaxKind
                                                                                        .SimpleMemberAccessExpression,
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "sr"),
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "ReadToEnd")
                                                                                )
                                                                        )
                                                                )
                                                            )
                                                    )
                                            )
                                    ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                    SyntaxFactory.VariableDeclaration(
                                        SyntaxFactory.IdentifierName(
                                            SyntaxFactory.Identifier(
                                                SyntaxFactory.TriviaList(),
                                                SyntaxKind.VarKeyword,
                                                "var",
                                                "var",
                                                SyntaxFactory.TriviaList()
                                            )
                                        )
                                    )
                                    .WithVariables(
                                        SyntaxFactory.SingletonSeparatedList<VariableDeclaratorSyntax>(
                                            SyntaxFactory.VariableDeclarator(
                                                SyntaxFactory.Identifier("obj")
                                            )
                                            .WithInitializer(
                                                SyntaxFactory.EqualsValueClause(
                                                    SyntaxFactory.InvocationExpression(
                                                        SyntaxFactory.MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            SyntaxFactory.MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                SyntaxFactory.MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    SyntaxFactory.IdentifierName("Newtonsoft"),
                                                                    SyntaxFactory.IdentifierName("Json")
                                                                ),
                                                                SyntaxFactory.IdentifierName("JsonConvert")
                                                            ),
                                                            SyntaxFactory.GenericName(
                                                                SyntaxFactory.Identifier("DeserializeObject")
                                                            )
                                                            .WithTypeArgumentList(
                                                                SyntaxFactory.TypeArgumentList(
                                                                    SyntaxFactory.SingletonSeparatedList<TypeSyntax>(
                                                                        SyntaxFactory.IdentifierName(methodDeclaration.ReturnType)
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                    .WithArgumentList(
                                                        SyntaxFactory.ArgumentList(
                                                            SyntaxFactory.SingletonSeparatedList<ArgumentSyntax>(
                                                                SyntaxFactory.Argument(
                                                                    SyntaxFactory.IdentifierName("output")
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ),
                                    SyntaxFactory.ExpressionStatement(
                                        SyntaxFactory.InvocationExpression(
                                            SyntaxFactory.MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                SyntaxFactory.IdentifierName("sr"),
                                                SyntaxFactory.IdentifierName("Close")
                                            )
                                        )
                                    ),
                                    SyntaxFactory.ReturnStatement(
                                        SyntaxFactory.IdentifierName("obj")
                                    )
                                )
                            ).NormalizeWhitespace();

                    methods[globalI] = method;
                    globalI++;
                }
                else if (methodDeclaration.HttpMethodName == "post")
                {
                    var method =
                        SyntaxFactory.MethodDeclaration(
                                SyntaxFactory.PredefinedType(
                                    SyntaxFactory.Token(SyntaxKind.VoidKeyword)
                                ),
                                SyntaxFactory.Identifier(methodDeclaration.MethodName)
                            )
                            .WithModifiers(
                                SyntaxFactory.TokenList(
                                    SyntaxFactory.Token(SyntaxKind.PublicKeyword)
                                )
                            )
                            .WithParameterList(
                                SyntaxFactory.ParameterList(
                                    SyntaxFactory.SingletonSeparatedList<ParameterSyntax>(
                                        SyntaxFactory.Parameter(
                                                SyntaxFactory.Identifier("obj")
                                            )
                                            .WithType(
                                                SyntaxFactory.IdentifierName(methodDeclaration.ArgList[0].Type)
                                            )
                                    )
                                )
                            )
                            .WithBody(
                                SyntaxFactory.Block(
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName(
                                                    SyntaxFactory.Identifier(
                                                        SyntaxFactory.TriviaList(),
                                                        SyntaxKind.VarKeyword,
                                                        "var",
                                                        "var",
                                                        SyntaxFactory.TriviaList()
                                                    )
                                                )
                                            )
                                            .WithVariables(
                                                SyntaxFactory
                                                    .SingletonSeparatedList<
                                                        VariableDeclaratorSyntax>(
                                                        SyntaxFactory.VariableDeclarator(
                                                                SyntaxFactory.Identifier(
                                                                    "httpWebRequest")
                                                            )
                                                            .WithInitializer(
                                                                SyntaxFactory
                                                                    .EqualsValueClause(
                                                                        SyntaxFactory
                                                                            .CastExpression(
                                                                                SyntaxFactory
                                                                                    .IdentifierName(
                                                                                        "HttpWebRequest"),
                                                                                SyntaxFactory
                                                                                    .InvocationExpression(
                                                                                        SyntaxFactory
                                                                                            .MemberAccessExpression(
                                                                                                SyntaxKind
                                                                                                    .SimpleMemberAccessExpression,
                                                                                                SyntaxFactory
                                                                                                    .IdentifierName(
                                                                                                        "WebRequest"),
                                                                                                SyntaxFactory
                                                                                                    .IdentifierName(
                                                                                                        "Create")
                                                                                            )
                                                                                    )
                                                                                    .WithArgumentList(
                                                                                        SyntaxFactory
                                                                                            .ArgumentList(
                                                                                                SyntaxFactory
                                                                                                    .SingletonSeparatedList
                                                                                                        <ArgumentSyntax>(
                                                                                                            SyntaxFactory
                                                                                                                .Argument(
                                                                                                                    SyntaxFactory
                                                                                                                        .LiteralExpression(
                                                                                                                            SyntaxKind
                                                                                                                                .StringLiteralExpression,
                                                                                                                            SyntaxFactory
                                                                                                                                .Literal(
                                                                                                                                    methodDeclaration.Url)
                                                                                                                        )
                                                                                                                )
                                                                                                        )
                                                                                            )
                                                                                    )
                                                                            )
                                                                    )
                                                            )
                                                    )
                                            )
                                    ),
                                    SyntaxFactory.ExpressionStatement(
                                        SyntaxFactory.AssignmentExpression(
                                            SyntaxKind.SimpleAssignmentExpression,
                                            SyntaxFactory.MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                SyntaxFactory.IdentifierName(
                                                    "httpWebRequest"),
                                                SyntaxFactory.IdentifierName("ContentType")
                                            ),
                                            SyntaxFactory.LiteralExpression(
                                                SyntaxKind.StringLiteralExpression,
                                                SyntaxFactory.Literal("application/json")
                                            )
                                        )
                                    ),
                                    SyntaxFactory.ExpressionStatement(
                                        SyntaxFactory.AssignmentExpression(
                                            SyntaxKind.SimpleAssignmentExpression,
                                            SyntaxFactory.MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                SyntaxFactory.IdentifierName(
                                                    "httpWebRequest"),
                                                SyntaxFactory.IdentifierName("Method")
                                            ),
                                            SyntaxFactory.LiteralExpression(
                                                SyntaxKind.StringLiteralExpression,
                                                SyntaxFactory.Literal("POST")
                                            )
                                        )
                                    ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName(
                                                    SyntaxFactory.Identifier(
                                                        SyntaxFactory.TriviaList(),
                                                        SyntaxKind.VarKeyword,
                                                        "var",
                                                        "var",
                                                        SyntaxFactory.TriviaList()
                                                    )
                                                )
                                            )
                                            .WithVariables(
                                                SyntaxFactory.SingletonSeparatedList<VariableDeclaratorSyntax>(
                                                    SyntaxFactory.VariableDeclarator(
                                                            SyntaxFactory.Identifier("dataJson")
                                                        )
                                                        .WithInitializer(
                                                            SyntaxFactory.EqualsValueClause(
                                                                SyntaxFactory.InvocationExpression(
                                                                        SyntaxFactory.MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            SyntaxFactory.MemberAccessExpression(
                                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                                SyntaxFactory.MemberAccessExpression(
                                                                                    SyntaxKind
                                                                                        .SimpleMemberAccessExpression,
                                                                                    SyntaxFactory.IdentifierName(
                                                                                        "Newtonsoft"),
                                                                                    SyntaxFactory.IdentifierName("Json")
                                                                                ),
                                                                                SyntaxFactory.IdentifierName(
                                                                                    "JsonConvert")
                                                                            ),
                                                                            SyntaxFactory.IdentifierName(
                                                                                "SerializeObject")
                                                                        )
                                                                    )
                                                                    .WithArgumentList(
                                                                        SyntaxFactory.ArgumentList(
                                                                            SyntaxFactory
                                                                                .SingletonSeparatedList<ArgumentSyntax>(
                                                                                    SyntaxFactory.Argument(
                                                                                        SyntaxFactory.IdentifierName(
                                                                                            "obj")
                                                                                    )
                                                                                )
                                                                        )
                                                                    )
                                                            )
                                                        )
                                                )
                                            )
                                    ),
                                    SyntaxFactory.UsingStatement(
                                            SyntaxFactory.Block(
                                                SyntaxFactory
                                                    .SingletonList<StatementSyntax>(
                                                        SyntaxFactory.ExpressionStatement(
                                                            SyntaxFactory
                                                                .InvocationExpression(
                                                                    SyntaxFactory
                                                                        .MemberAccessExpression(
                                                                            SyntaxKind
                                                                                .SimpleMemberAccessExpression,
                                                                            SyntaxFactory
                                                                                .IdentifierName(
                                                                                    "streamWriter"),
                                                                            SyntaxFactory
                                                                                .IdentifierName(
                                                                                    "Write")
                                                                        )
                                                                )
                                                                .WithArgumentList(
                                                                    SyntaxFactory
                                                                        .ArgumentList(
                                                                            SyntaxFactory
                                                                                .SingletonSeparatedList
                                                                                    <ArgumentSyntax>(
                                                                                        SyntaxFactory
                                                                                            .Argument(
                                                                                                SyntaxFactory
                                                                                                    .IdentifierName(
                                                                                                        "dataJson")
                                                                                            )
                                                                                    )
                                                                        )
                                                                )
                                                        )
                                                    )
                                            )
                                        )
                                        .WithDeclaration(
                                            SyntaxFactory.VariableDeclaration(
                                                    SyntaxFactory.IdentifierName(
                                                        SyntaxFactory.Identifier(
                                                            SyntaxFactory.TriviaList(),
                                                            SyntaxKind.VarKeyword,
                                                            "var",
                                                            "var",
                                                            SyntaxFactory.TriviaList()
                                                        )
                                                    )
                                                )
                                                .WithVariables(
                                                    SyntaxFactory
                                                        .SingletonSeparatedList<
                                                            VariableDeclaratorSyntax>(
                                                            SyntaxFactory
                                                                .VariableDeclarator(
                                                                    SyntaxFactory
                                                                        .Identifier(
                                                                            "streamWriter")
                                                                )
                                                                .WithInitializer(
                                                                    SyntaxFactory
                                                                        .EqualsValueClause(
                                                                            SyntaxFactory
                                                                                .ObjectCreationExpression(
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "StreamWriter")
                                                                                )
                                                                                .WithArgumentList(
                                                                                    SyntaxFactory
                                                                                        .ArgumentList(
                                                                                            SyntaxFactory
                                                                                                .SingletonSeparatedList
                                                                                                    <ArgumentSyntax>(
                                                                                                        SyntaxFactory
                                                                                                            .Argument(
                                                                                                                SyntaxFactory
                                                                                                                    .InvocationExpression(
                                                                                                                        SyntaxFactory
                                                                                                                            .MemberAccessExpression(
                                                                                                                                SyntaxKind
                                                                                                                                    .SimpleMemberAccessExpression,
                                                                                                                                SyntaxFactory
                                                                                                                                    .IdentifierName(
                                                                                                                                        "httpWebRequest"),
                                                                                                                                SyntaxFactory
                                                                                                                                    .IdentifierName(
                                                                                                                                        "GetRequestStream")
                                                                                                                            )
                                                                                                                    )
                                                                                                            )
                                                                                                    )
                                                                                        )
                                                                                )
                                                                        )
                                                                )
                                                        )
                                                )
                                        ),
                                    SyntaxFactory.LocalDeclarationStatement(
                                        SyntaxFactory.VariableDeclaration(
                                                SyntaxFactory.IdentifierName(
                                                    SyntaxFactory.Identifier(
                                                        SyntaxFactory.TriviaList(),
                                                        SyntaxKind.VarKeyword,
                                                        "var",
                                                        "var",
                                                        SyntaxFactory.TriviaList()
                                                    )
                                                )
                                            )
                                            .WithVariables(
                                                SyntaxFactory
                                                    .SingletonSeparatedList<
                                                        VariableDeclaratorSyntax>(
                                                        SyntaxFactory.VariableDeclarator(
                                                                SyntaxFactory.Identifier(
                                                                    "httpResponse")
                                                            )
                                                            .WithInitializer(
                                                                SyntaxFactory
                                                                    .EqualsValueClause(
                                                                        SyntaxFactory
                                                                            .CastExpression(
                                                                                SyntaxFactory
                                                                                    .IdentifierName(
                                                                                        "HttpWebResponse"),
                                                                                SyntaxFactory
                                                                                    .InvocationExpression(
                                                                                        SyntaxFactory
                                                                                            .MemberAccessExpression(
                                                                                                SyntaxKind
                                                                                                    .SimpleMemberAccessExpression,
                                                                                                SyntaxFactory
                                                                                                    .IdentifierName(
                                                                                                        "httpWebRequest"),
                                                                                                SyntaxFactory
                                                                                                    .IdentifierName(
                                                                                                        "GetResponse")
                                                                                            )
                                                                                    )
                                                                            )
                                                                    )
                                                            )
                                                    )
                                            )
                                    ),
                                    SyntaxFactory.UsingStatement(
                                            SyntaxFactory.Block(
                                                SyntaxFactory
                                                    .SingletonList<StatementSyntax>(
                                                        SyntaxFactory
                                                            .LocalDeclarationStatement(
                                                                SyntaxFactory
                                                                    .VariableDeclaration(
                                                                        SyntaxFactory
                                                                            .IdentifierName(
                                                                                SyntaxFactory
                                                                                    .Identifier(
                                                                                        SyntaxFactory
                                                                                            .TriviaList(),
                                                                                        SyntaxKind
                                                                                            .VarKeyword,
                                                                                        "var",
                                                                                        "var",
                                                                                        SyntaxFactory
                                                                                            .TriviaList()
                                                                                    )
                                                                            )
                                                                    )
                                                                    .WithVariables(
                                                                        SyntaxFactory
                                                                            .SingletonSeparatedList
                                                                                <VariableDeclaratorSyntax>(
                                                                                    SyntaxFactory
                                                                                        .VariableDeclarator(
                                                                                            SyntaxFactory
                                                                                                .Identifier(
                                                                                                    "result")
                                                                                        )
                                                                                        .WithInitializer(
                                                                                            SyntaxFactory
                                                                                                .EqualsValueClause(
                                                                                                    SyntaxFactory
                                                                                                        .InvocationExpression(
                                                                                                            SyntaxFactory
                                                                                                                .MemberAccessExpression(
                                                                                                                    SyntaxKind
                                                                                                                        .SimpleMemberAccessExpression,
                                                                                                                    SyntaxFactory
                                                                                                                        .IdentifierName(
                                                                                                                            "streamReader"),
                                                                                                                    SyntaxFactory
                                                                                                                        .IdentifierName(
                                                                                                                            "ReadToEnd")
                                                                                                                )
                                                                                                        )
                                                                                                )
                                                                                        )
                                                                                )
                                                                    )
                                                            )
                                                    )
                                            )
                                        )
                                        .WithDeclaration(
                                            SyntaxFactory.VariableDeclaration(
                                                    SyntaxFactory.IdentifierName(
                                                        SyntaxFactory.Identifier(
                                                            SyntaxFactory.TriviaList(),
                                                            SyntaxKind.VarKeyword,
                                                            "var",
                                                            "var",
                                                            SyntaxFactory.TriviaList()
                                                        )
                                                    )
                                                )
                                                .WithVariables(
                                                    SyntaxFactory
                                                        .SingletonSeparatedList<
                                                            VariableDeclaratorSyntax>(
                                                            SyntaxFactory
                                                                .VariableDeclarator(
                                                                    SyntaxFactory
                                                                        .Identifier(
                                                                            "streamReader")
                                                                )
                                                                .WithInitializer(
                                                                    SyntaxFactory
                                                                        .EqualsValueClause(
                                                                            SyntaxFactory
                                                                                .ObjectCreationExpression(
                                                                                    SyntaxFactory
                                                                                        .IdentifierName(
                                                                                            "StreamReader")
                                                                                )
                                                                                .WithArgumentList(
                                                                                    SyntaxFactory
                                                                                        .ArgumentList(
                                                                                            SyntaxFactory
                                                                                                .SingletonSeparatedList
                                                                                                    <ArgumentSyntax>(
                                                                                                        SyntaxFactory
                                                                                                            .Argument(
                                                                                                                SyntaxFactory
                                                                                                                    .InvocationExpression(
                                                                                                                        SyntaxFactory
                                                                                                                            .MemberAccessExpression(
                                                                                                                                SyntaxKind
                                                                                                                                    .SimpleMemberAccessExpression,
                                                                                                                                SyntaxFactory
                                                                                                                                    .IdentifierName(
                                                                                                                                        "httpResponse"),
                                                                                                                                SyntaxFactory
                                                                                                                                    .IdentifierName(
                                                                                                                                        "GetResponseStream")
                                                                                                                            )
                                                                                                                    )
                                                                                                            )
                                                                                                    )
                                                                                        )
                                                                                )
                                                                        )
                                                                )
                                                        )
                                                )
                                        )
                                )
                            ).NormalizeWhitespace();
                    
                    methods[globalI] = method;
                    globalI++;
                }
            }


            var classOwner = GenerateClassEntity("/Users/kate/Desktop/demo/src/main/java/com/example/demo/entity/Owner.java", 
                "Owner");

            var classPet = GenerateClassEntity("/Users/kate/Desktop/demo/src/main/java/com/example/demo/entity/Pet.java", 
                "Pet");

            
            var result = SyntaxFactory.CompilationUnit()
                .WithUsings(
                    SyntaxFactory.List<UsingDirectiveSyntax>(
                        new UsingDirectiveSyntax[]
                        {
                            SyntaxFactory.UsingDirective(
                                SyntaxFactory.IdentifierName("System")
                            ),
                            SyntaxFactory.UsingDirective(
                                SyntaxFactory.QualifiedName(
                                    SyntaxFactory.IdentifierName("System"),
                                    SyntaxFactory.IdentifierName("IO")
                                )
                            ),
                            SyntaxFactory.UsingDirective(
                                SyntaxFactory.QualifiedName(
                                    SyntaxFactory.IdentifierName("System"),
                                    SyntaxFactory.IdentifierName("Net")
                                )
                            )
                        }
                    )
                )
                .AddMembers(

                    SyntaxFactory.NamespaceDeclaration(
                            SyntaxFactory.IdentifierName("JavaProject")
                        )
                        .AddMembers(classOwner)
                        .AddMembers(classPet)
                        .AddMembers(
                            SyntaxFactory.ClassDeclaration("MyProject")
                                .AddMembers(
                                    methods
                                )
                        )
                )

                .NormalizeWhitespace();
            context.AddSource("imay.g.cs", result.ToString());
        }


        public ClassDeclarationSyntax GenerateClassEntity(string path, string nameClass)
        {
            JavaParser parser = new JavaParser();
            List<ArgDeclaration> property = parser.ParserEntity(path);

            var propertyDeclarationArray = new MemberDeclarationSyntax[property.Count];
            int countProperty = 0;
            foreach (var arg in property)
            {
                var propertyDeclaration = SyntaxFactory.PropertyDeclaration(
                        SyntaxFactory.IdentifierName(arg.Type),
                        SyntaxFactory.Identifier(arg.Name)
                    )
                    .WithModifiers(
                        SyntaxFactory.TokenList(
                            SyntaxFactory.Token(SyntaxKind.PublicKeyword)
                        )
                    )
                    .WithAccessorList(
                        SyntaxFactory.AccessorList(
                            SyntaxFactory.List<AccessorDeclarationSyntax>(
                                new AccessorDeclarationSyntax[]
                                {
                                    SyntaxFactory.AccessorDeclaration(
                                            SyntaxKind.GetAccessorDeclaration
                                        )
                                        .WithSemicolonToken(
                                            SyntaxFactory.Token(SyntaxKind.SemicolonToken)
                                        ),
                                    SyntaxFactory.AccessorDeclaration(
                                            SyntaxKind.SetAccessorDeclaration
                                        )
                                        .WithSemicolonToken(
                                            SyntaxFactory.Token(SyntaxKind.SemicolonToken)
                                        )
                                }
                            )
                        )
                    ).NormalizeWhitespace();

                propertyDeclarationArray[countProperty] = propertyDeclaration;
                countProperty++;
            }


            ClassDeclarationSyntax classEntity = SyntaxFactory.ClassDeclaration(nameClass)
                .WithMembers(
                    SyntaxFactory.List(
                        propertyDeclarationArray
                    )
                ).NormalizeWhitespace();

            return classEntity;
        }
    }
}